[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"
